# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R73HBpwkNGGYBruikuF6OGjJzSOTCRgY
"""

import io
from typing import Dict, Tuple, Optional, Any

import numpy as np
import streamlit as st
from PIL import Image

# ============================
# MINIMAL EDIT ZONE (2 cosas)
# 1) Ajusta imports a tu repo
# 2) Ajusta labels si hace falta
# ============================

# Labels esperados (si tu predict devuelve dict probs {label: prob}, no los necesitas)
DEFAULT_LABELS = ["glioma", "meningioma", "pituitary", "no_tumor"]

# Intenta importar funciones "reales" (contratos del equipo)
# Contratos:
#   predict_pil(pil_img) -> (probs_dict, pred_label)
#       - probs_dict: Dict[str, float]  (p.ej. {"glioma":0.1, ...})
#       - pred_label: str
#   gradcam_overlay(pil_img) -> (overlay_pil, heatmap_np)
#       - overlay_pil: PIL.Image
#       - heatmap_np: np.ndarray (H,W) float [0,1] (ideal), pero si no: igual lo mostramos
#
#  👉 EDITA ESTAS RUTAS si tus archivos están en otro lado.
try:
    from src.models.infer import predict_pil  # type: ignore
    from src.explain.gradcam import gradcam_overlay  # type: ignore
    REAL_PIPELINE = True
except Exception:
    REAL_PIPELINE = False

# Opcional: si existe el agente (Rol Text Explainer)
# explain(pred_label, probs_dict, heatmap_features) -> str
try:
    from src.explain.text_agent import explain  # type: ignore
    TEXT_AGENT_AVAILABLE = True
except Exception:
    TEXT_AGENT_AVAILABLE = False


# ============================
# Fallbacks (MOCK) para no bloquear
# ============================

def _mock_predict_pil(_: Image.Image) -> Tuple[Dict[str, float], str]:
    # Mock consistente (ajústalo si quieres)
    probs = {"glioma": 0.10, "meningioma": 0.08, "pituitary": 0.05, "no_tumor": 0.77}
    pred = max(probs, key=probs.get)
    return probs, pred

def _mock_gradcam_overlay(pil_img: Image.Image) -> Tuple[Image.Image, np.ndarray]:
    # Heatmap circular fake + overlay simple para UI
    img = pil_img.convert("RGB")
    w, h = img.size
    yy, xx = np.mgrid[0:h, 0:w]
    cx, cy = int(w * 0.55), int(h * 0.52)
    dist = np.sqrt((xx - cx) ** 2 + (yy - cy) ** 2)
    heatmap = np.exp(-(dist ** 2) / (2 * (0.18 * min(w, h)) ** 2))
    heatmap = (heatmap - heatmap.min()) / (heatmap.max() - heatmap.min() + 1e-8)

    img_np = np.array(img).astype(np.float32)
    hm_rgb = np.stack([heatmap, np.zeros_like(heatmap), 1 - heatmap], axis=-1) * 255.0
    overlay_np = (0.65 * img_np + 0.35 * hm_rgb).clip(0, 255).astype(np.uint8)
    return Image.fromarray(overlay_np), heatmap.astype(np.float32)

def _basic_heatmap_features(heatmap: np.ndarray) -> Dict[str, Any]:
    # Features mínimos para el agente (si no hay extractor todavía)
    hm = np.array(heatmap, dtype=np.float32)
    if hm.ndim == 3:
        hm = hm[..., 0]
    hm = np.nan_to_num(hm, nan=0.0, posinf=0.0, neginf=0.0)

    # Normaliza si viene raro
    if hm.max() > 1.0:
        hm = hm / (hm.max() + 1e-8)

    thr = 0.6
    focus_ratio = float((hm > thr).mean())
    peak = float(hm.max())

    h, w = hm.shape
    y, x = np.mgrid[0:h, 0:w]
    total = float(hm.sum() + 1e-8)
    com_x = float((x * hm).sum() / total)
    com_y = float((y * hm).sum() / total)

    # num_regions: lo dejamos como None si no hay skimage/scipy
    return {
        "focus_ratio": focus_ratio,
        "num_regions": None,
        "center_of_mass": (com_x, com_y),
        "peak_intensity": peak,
    }

def _mock_explain(pred_label: str, probs: Dict[str, float], heatmap_features: Dict[str, Any]) -> str:
    items = sorted(probs.items(), key=lambda x: x[1], reverse=True)
    top1_label, top1 = items[0]
    top2 = items[1][1] if len(items) > 1 else 0.0
    margin = top1 - top2

    if top1 >= 0.80 and margin >= 0.20:
        conf = "High"
    elif top1 >= 0.60:
        conf = "Medium"
    else:
        conf = "Low"

    focus_ratio = float(heatmap_features.get("focus_ratio", 0.0))
    pattern = "localized" if focus_ratio < 0.18 else "diffuse"

    return (
        f"The model predicts **{pred_label}** with **{top1:.1%}** confidence ({conf}).\n\n"
        f"Attention appears **{pattern}** (focus_ratio={focus_ratio:.2f}), suggesting the prediction relied on "
        f"{'focal regions' if pattern=='localized' else 'broader/global patterns'}.\n\n"
        f"If confidence is low, interpret cautiously.\n\n"
        f"**Disclaimer:** Educational/research use only. Not for medical diagnosis."
    )


# ============================
# Streamlit UI
# ============================

st.set_page_config(page_title="Brain Tumor XAI Assistant", layout="wide")

st.title("🧠 Explainable Brain Tumor Detection Assistant")
st.caption("Upload MRI → predict + Grad-CAM overlay + explanation text (baseline).")

st.markdown(
    """
**Medical Disclaimer:** This tool is for educational/research purposes only and is **not** a medical diagnostic device.
Do not use it for clinical decision-making.
"""
)

with st.expander("⚙️ Settings", expanded=False):
    force_mock = st.checkbox("Force MOCK mode (ignore real functions)", value=False)
    show_heatmap_raw = st.checkbox("Show raw heatmap (debug)", value=True)
    top_k = st.slider("Top-k probabilities to display", min_value=2, max_value=6, value=4)

uploaded = st.file_uploader("Upload MRI image (png/jpg)", type=["png", "jpg", "jpeg"])

if uploaded is None:
    st.info("Upload an image to start. UI works even if model/Grad-CAM are not ready (MOCK mode).")
    st.stop()

# Load image
pil_img = Image.open(uploaded).convert("RGB")

c1, c2 = st.columns([1, 1])
with c1:
    st.subheader("1) Input")
    st.image(pil_img, use_container_width=True)

analyze = st.button("🔍 Analyze", type="primary")

if not analyze:
    st.stop()

use_real = REAL_PIPELINE and (not force_mock)

with st.spinner("Running inference..."):
    # 1) Predict
    if use_real:
        probs_dict, pred_label = predict_pil(pil_img)
    else:
        probs_dict, pred_label = _mock_predict_pil(pil_img)

    # 2) Grad-CAM overlay
    if use_real:
        try:
            overlay_pil, heatmap = gradcam_overlay(pil_img)
        except Exception:
            # Si gradcam aún está inestable, no bloqueamos
            overlay_pil, heatmap = _mock_gradcam_overlay(pil_img)
    else:
        overlay_pil, heatmap = _mock_gradcam_overlay(pil_img)

    # 3) Features (mínimas para agente)
    heatmap_features = _basic_heatmap_features(heatmap)

    # 4) Explanation text
    if TEXT_AGENT_AVAILABLE and use_real:
        try:
            explanation_text = explain(pred_label, probs_dict, heatmap_features)
        except Exception:
            explanation_text = _mock_explain(pred_label, probs_dict, heatmap_features)
    else:
        explanation_text = _mock_explain(pred_label, probs_dict, heatmap_features)

# ----------------------------
# Results UI
# ----------------------------
with c2:
    st.subheader("2) Prediction")

    # Top-1
    top1_prob = float(probs_dict.get(pred_label, max(probs_dict.values()) if probs_dict else 0.0))
    st.markdown(f"**Predicted class:** `{pred_label}`")
    st.markdown(f"**Top-1 probability:** `{top1_prob:.3f}`")

    # Table + bar chart
    st.write("**Class probabilities**")
    # Ensure stable order
    labels = list(probs_dict.keys()) if probs_dict else DEFAULT_LABELS
    ordered = sorted(probs_dict.items(), key=lambda x: x[1], reverse=True)
    ordered = ordered[: min(top_k, len(ordered))]

    table_data = [{"label": k, "prob": float(v)} for k, v in ordered]
    st.dataframe(table_data, use_container_width=True, hide_index=True)

    # Bar chart expects a series-like structure
    chart_labels = [k for k, _ in ordered]
    chart_vals = [float(v) for _, v in ordered]
    st.bar_chart({"probability": chart_vals}, x=chart_labels)

st.divider()

c3, c4 = st.columns([1, 1])
with c3:
    st.subheader("3) Grad-CAM Overlay (baseline ok)")
    st.image(overlay_pil, use_container_width=True)

with c4:
    st.subheader("4) Explanation")
    st.markdown(explanation_text)

    with st.expander("Debug: heatmap features", expanded=False):
        st.json(heatmap_features)

if show_heatmap_raw:
    st.subheader("Heatmap (raw / debug)")
    # Streamlit can display 2D arrays as images
    hm = np.array(heatmap, dtype=np.float32)
    if hm.ndim == 3:
        hm = hm[..., 0]
    st.image(hm, clamp=True, use_container_width=True)

# Simple report download (optional baseline)
st.divider()
st.subheader("📄 Download")
report = f"""Brain Tumor XAI Assistant Report

Predicted class: {pred_label}
Top-1 probability: {top1_prob:.4f}

Probabilities:
{json.dumps(probs_dict, indent=2)}

Heatmap features:
{json.dumps(heatmap_features, indent=2, default=str)}

Explanation:
{explanation_text}

Disclaimer:
Educational/research only. Not a medical diagnosis.
"""
st.download_button(
    "Download report (TXT)",
    data=report.encode("utf-8"),
    file_name="report.txt",
    mime="text/plain",
)